kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.11.3/deploy/static/provider/cloud/deploy.yaml
----------------------------------------
kubectl apply -f deploy.yaml # deploy and service (service name = nginx-service *** )
kubectl apply -f nginx-ing.yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ing
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: localhost
      http:
        paths:
          - path: / # or /test or waht you want
            pathType: Prefix
            backend:
              service:
                name: nginx-service  # connect to our service ***
                port:
                  number: 80
