kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.11.3/deploy/static/provider/cloud/deploy.yaml
----------------------------------------
kubectl apply -f deploy.yaml # deploy and service (service name = nginx-service *** )
kubectl apply -f nginx-ing.yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ing
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: localhost
      http:
        paths:
          - path: / # or /test or waht you want
            pathType: Prefix
            backend:
              service:
                name: nginx-service  # connect to our service ***
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend: { service: { name: api-svc, port: { number: 80 } } }
          - path: /web
            pathType: Prefix
            backend: { service: { name: web-svc, port: { number: 80 } } }
------------------------------ With HTTPS ------------------------------------------------------------------------------
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout cert.key -out cert.crt -subj "/CN=local/983O=MyOrg"
kubectl create secret tls my-tls --cert=cert.crt --key=cert.key -n default
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ing
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
    - hosts: # if you need https
        - localhost
      secretName: my-tls
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80

