ConfigMap
  - Key/Value
  - File
----------------------------- Key/Value---------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: color-config
data:
  APP_COLOR: "blue"
  APP_VERSION: "1.0"
---
apiVersion: v1
kind: Pod
metadata:
  name: env-demo
spec:
  containers:
    - name: app
      image: nginx
      env:
        - name: COLOR
          valueFrom:
            configMapKeyRef: #------------
              name: color-config #------------
              key: APP_COLOR #------------
------------------------------File-----------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: file-config
data:
  config.ini: |
    PORT=8080
    LOG_LEVEL=info
---
apiVersion: v1
kind: Pod
metadata:
  name: file-demo
spec:
  containers:
    - name: app
      image: nginx
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config # ----> file will save here in container (/etc/config/config.ini)
  volumes:
    - name: config-volume
      configMap:
        name: file-config #------------ ConfigMap Name
